[project]
name = "php-parser-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SamHsu", email = "yxu166@jh.edu" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
